# Generated by Django 4.1.4 on 2022-12-09 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=244)),
                ('last_name', models.CharField(max_length=244)),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('old', models.IntegerField()),
                ('phone', models.CharField(max_length=24)),
            ],
        ),
    ]
